from enum import StrEnum


class GraphOperation(StrEnum):
    SIMILAR_USER_SEARCH = "SIMILAR_USER_SEARCH"
    USER_HOTEL_RETRIEVAL = "USER_HOTEL_RETRIEVAL"
    HOTEL_SIMILARITY_SEARCH = "HOTEL_SIMILARITY_SEARCH"
    HOTEL_FEATURE_DISCOVERY = "HOTEL_FEATURE_DISCOVERY"
