from enum import StrEnum


class SearchTask(StrEnum):
    INFORMATION = "INFORMATION"
    HOTEL_SEARCH = "HOTEL_SEARCH"
    HOTEL_SIMILAR = "HOTEL_SIMILAR"
    TRENDING = "TRENDING"
    PERSONALIZATION = "PERSONALIZATION"
    SPECIAL_FEATURE = "SPECIAL_FEATURE"
